gip-inclusion/dora-front

- src/lib/components/link-button.svelte
- src/lib/components/nav-item.svelte
- src/routes/_layout/_footer.svelte
- src/routes/_layout/_top-links.svelte
A terme il faudra sans doute revoir la difference entre NavItems et LinkButtons, voire encapsuler les `<a>`
> Evite de recharger les pages lors de la navigation interne #12

- .storybook/main.cjs
- src/lib/components/forms/fieldset.svelte
- src/lib/components/forms/input.svelte
- src/lib/components/forms/simple-autocomplete.svelte
- src/lib/components/link-button.svelte
- src/lib/components/structures/form-wrapper.svelte
- src/lib/components/structures/search-by-commune.svelte
- src/lib/components/structures/search-by-siret.svelte
- src/lib/components/structures/search.svelte
- src/lib/components/tabs.svelte
- src/lib/components/tag.svelte
- src/routes/auth/registration/_step3-other.svelte
- src/routes/contribuer/form/_step1.svelte
- src/routes/services/[slug]/_service-card.svelte
- src/routes/services/[slug]/_service-header.svelte
- src/routes/services/[slug]/_service-presentation.svelte
- src/routes/tableau-de-bord/structures/[slug]/index.svelte
- src/routes/tableau-de-bord/structures/creer/index.svelte
La recherche par structure est modifiée a deux endroits : 
- lors de la contribution
- lors de l'ajout de structure. 
oncernant la création de profil, je n'ai pas encore modifié. 
La requête sur `search-all-sirene` est super lente et pas vraiment utilisable en l'etat.
> Met à jour la recherche de structure

- package-lock.json
- package.json
- src/lib/components/nav-item.svelte
- src/lib/components/rich-text/editor.svelte
- src/lib/icons.js
- src/lib/services.js
- src/lib/utils.js
- src/routes/services/[slug]/_service-presentation.svelte
- src/routes/structures/[slug]/_structure-pres.svelte
mvp: ça marche avec une `window.prompt` pour l'instant
> feat(editeur de texte): ajoute une option pour mettre des liens

- src/lib/services.js
Lié à https://github.com/betagouv/dora-back/pull/13
> feat: assure la rétrocompatibilité après mise à jour du backend

- src/lib/schemas/service.js
- src/routes/_homepage/_search-form.svelte
- src/routes/_homepage/_search_tweak_form.svelte
- src/routes/contribuer/form/_step2.svelte
- src/routes/recherche.svelte
- src/routes/services/[slug]/_modalities-box.svelte
- src/routes/services/form/_step3.svelte
- src/routes/services/form/_step4.svelte
Back: https://github.com/betagouv/dora-back/pull/16
> chore: mise à jour des identifiants des énumérations

- src/lib/components/forms/city-search.svelte
- src/lib/components/structures/search-by-commune.svelte
- src/routes/_homepage/_search-form.svelte
- src/routes/_homepage/_search_tweak_form.svelte
- src/routes/contribuer/form/_step2.svelte
- src/routes/services/form/_step4.svelte
- src/routes/structures/creer/index.svelte
Pour les recherches de communes.
~~Necessite https://github.com/betagouv/dora-back/pull/27 coté back.~~
Utile pour https://www.notion.so/dora-beta/Arrondissement-Zone-de-diffusion-8c16cf03c9484975ae20009c9c8d4912
et https://www.notion.so/dora-beta/La-recherche-SIRET-ne-fonctionne-pas-dans-les-villes-arrondissement-496177d45ec849d5a06347a8781691ad
> chore: utilise notre api admin express plutot que la ban

- src/lib/components/forms/city-search.svelte
- src/lib/components/structures/search-by-commune.svelte
- src/routes/_homepage/_search-form.svelte
- src/routes/_homepage/_search_tweak_form.svelte
- src/routes/contribuer/form/_step2.svelte
- src/routes/services/form/_step4.svelte
- src/routes/structures/creer/index.svelte
En attendant que ce commit soit mergee sur le back:
https://github.com/betagouv/dora-back/commit/9683e9d7f32d7306f735338c150388976b976f44
> revert: utilise l'api adresse pour la localisation

- src/routes/_homepage/_search-form.svelte
Note : je n'ai pas osé touché au bouton de `submit` (un peu -trop- de niveau d'imbrication)
https://user-images.githubusercontent.com/1846641/177348201-0f94bb97-fe06-4a82-a64e-c9a555df391f.mp4
> fix(homepage): correction du design cassé du formulaire de recherche

- src/lib/components/link-button.svelte
Bon, il faut faire un test e2e de tout ça un jour !
> fix(mobiliser): réparation du tracking plausible

- src/hooks.js
- src/lib/components/tally-nps-popup.svelte
- src/lib/const.js
- src/routes/__layout.svelte
- src/routes/recherche.svelte
- src/routes/services/[slug]/index.svelte
- src/routes/structures/[slug]/index.svelte
Ajout du formulaire de NPS (`embed.js` via Tally)
> feat(nps): ajout formulaire NPS

- src/lib/components/services/service-body.svelte
https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=3baa9c2938674ce591cf155da7e5d59a
Avant :
Après :
> feat: meilleur intitulé des liens de téléchargement

- src/routes/__layout.svelte
- src/routes/_layout/_skip-link.svelte
https://www.accede-web.com/notices/html-et-css/navigation-au-clavier/mettre-en-place-un-lien-devitement/
> feat(a11y): ajout de lien d'évitement

- src/lib/services.js
- src/lib/structures.js
- src/routes/auth/accepter-invitation.svelte
- src/routes/auth/reinitialiser-mdp.svelte
- src/routes/auth/validation-email.svelte
- src/routes/index.svelte
- src/routes/modeles/[slug]/editer.svelte
- src/routes/modeles/[slug]/index.svelte
- src/routes/modeles/creer.svelte
- src/routes/recherche.svelte
- src/routes/services/[slug]/editer.svelte
- src/routes/services/[slug]/index.svelte
- src/routes/services/creer.svelte
- src/routes/structures/[slug]/__layout.svelte
- src/routes/structures/[slug]/collaborateurs/index.svelte
- src/routes/structures/[slug]/editer.svelte
- src/routes/structures/[slug]/services/index.svelte
- src/routes/structures/creer/index.svelte
Un peu en relation avec
https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=c0611ab478314eadb9248507bc253b6e&pm=s
... mais pas totalement. :)
> Utilisation de kitFetch partout

- src/lib/services.js
- src/lib/structures.js
- src/routes/auth/accepter-invitation.svelte
- src/routes/auth/reinitialiser-mdp.svelte
- src/routes/auth/validation-email.svelte
- src/routes/index.svelte
- src/routes/modeles/[slug]/editer.svelte
- src/routes/modeles/[slug]/index.svelte
- src/routes/modeles/creer.svelte
- src/routes/recherche.svelte
- src/routes/services/[slug]/editer.svelte
- src/routes/services/[slug]/index.svelte
- src/routes/services/creer.svelte
- src/routes/structures/[slug]/__layout.svelte
- src/routes/structures/[slug]/collaborateurs/index.svelte
- src/routes/structures/[slug]/editer.svelte
- src/routes/structures/[slug]/services/index.svelte
- src/routes/structures/creer/index.svelte
This reverts commit 563e41d0663800adf6e381e288120bd622a68ee6.
> Revert "Utilisation de kitFetch partout (#97)"

- src/lib/components/modal.svelte
- src/lib/components/services/body/service-contact.svelte
- src/lib/components/services/body/service-key-informations.svelte
- src/lib/components/services/icons/synchronized.svelte
- src/lib/components/services/service-toolbar.svelte
- src/lib/components/services/service-update-status-as-contributor.svelte
- src/lib/components/services/set-as-updated-modal.svelte
- src/lib/icons.js
- src/lib/types.ts
- src/lib/utils/phone.ts
https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=833b4239084a4fbe8fbbffcca4fd2c16&pm=s
> feat(actualisation) : modale de mise à jour

- src/lib/schemas/service.js
Carto numérique => part 2 - prio 3
https://www.notion.so/dora-beta/Carto-numQ-Prio-2-Blocage-th-matique-d-un-mod-le-2f0c8f121cee49429050aa8eb24b0565
> Besoins et type optionnel pour un modèle

- src/lib/components/form/openingHours/day-field.svelte
- src/lib/components/form/select-field.svelte
- src/lib/components/structures/form-wrapper.svelte
- src/lib/schemas/utils.js
- src/routes/structures/[slug]/_informations.svelte
- src/routes/structures/[slug]/index.svelte
https://www.notion.so/dora-beta/Carto-numQ-Prio-1-Champs-Structure-9a22bc393a154406b23840c250d8c823
> Correction pour la carto numérique

- src/lib/components/services/form/_fields-common.svelte
- src/lib/components/services/form/service-fields.svelte
- src/lib/schemas/service.js
- src/lib/validation.js
https://www.notion.so/dora-beta/Carto-numQ-Prio-2-Blocage-th-matique-d-un-mod-le-2f0c8f121cee49429050aa8eb24b0565
> Correction autour du blocage des thématiques dans un modèle

- package-lock.json
- package.json
- src/lib/components/button.svelte
- src/lib/components/modal.svelte
- src/lib/components/users/modal-add-user.svelte
https://www.notion.so/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=8ce1f07c09ec48dfb03d802bf92a47cd&pm=s
> Modal accessible au clavier

- e2e/mocks/mockService.js
- src/lib/components/form/field-wrapper.svelte
- src/lib/components/form/select-field.svelte
- src/lib/components/services/body/service-key-informations.svelte
- src/lib/components/services/body/toolbar/service-toolbar.svelte
- src/lib/components/services/body/toolbar/service-update-status-as-contributor.svelte
- src/lib/components/services/form/_fields-common.svelte
- src/lib/components/services/model-body.svelte
- src/lib/components/services/service-button-menu.svelte
- src/lib/components/services/service-menu.svelte
- src/lib/components/services/set-as-updated-modal.svelte
- src/lib/schemas/service.js
- src/lib/services.js
- src/lib/types.ts
- src/lib/utils/choice.ts
- src/lib/utils/service/index.ts
- src/routes/_homepage/_search.js
- src/routes/_homepage/_search_tweak_form.svelte
- src/routes/admin/contributions/_suggestion-modal.svelte
- src/routes/admin/services/[slug]/index.svelte
- src/routes/contribuer/form/_fields.svelte
- src/routes/modeles/[slug]/index.svelte
- src/routes/recherche.svelte
- src/routes/services/[slug]/index.svelte
=> https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=8bd2b92e04064c84b1e475e8b65c88e2&pm=s
> [Carto numQ-3] Frais à charge - Liste déroulante

- src/lib/components/services/body/toolbar/service-update-status-as-contributor.svelte
- src/lib/components/services/body/toolbar/service-update-status-as-reader.svelte
https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=5336cc7f905d4fb89207122b4e42f1ea&pm=s
> Affichage de la date en cas d'impression

- src/lib/components/services/body/service-share.svelte
- src/lib/utils/plausible.js
https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=9dad2fd3093041bd9393b7bd06aec027&pm=s
> Suivi du téléchargement des PDF

- src/lib/components/form/field-wrapper.svelte
- src/lib/components/form/select/select-field.svelte
- src/lib/components/form/select/select-label.svelte
- src/lib/components/services/form/_fields-common.svelte
- src/lib/components/structures/form-wrapper.svelte
- src/lib/icons.js
- src/lib/types.ts
- src/lib/utils/choice.ts
- src/lib/utils/service/index.ts
- src/routes/_homepage/_search_tweak_form.svelte
- src/routes/contribuer/form/_fields.svelte
- src/routes/structures/[slug]/services/_list.svelte
https://github.com/betagouv/dora-front/pull/119#issue-1399937768
> Ajout des filtres dans le tableau de bord offreur

- src/lib/components/services/body/presentation/service-presentation.svelte
https://www.notion.so/dora-beta/Alignement-des-types-d-aide-555aa0cb284c46a98677bb901104e9d2
> Ajout de flex-wrap

- src/routes/_homepage/_search.js
- src/routes/_homepage/_search_tweak_form.svelte
- src/routes/recherche.svelte
https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=8bd2b92e04064c84b1e475e8b65c88e2&pm=s
> Choix multiple pour les frais à charge

- src/lib/components/services/body/service-share.svelte
https://www.notion.so/dora-beta/Mettre-une-date-d-actualisation-absolue-plut-t-que-relative-sur-les-fiches-PDF-5336cc7f905d4fb89207122b4e42f1ea?d=6af3ba81391c4273b90ad6d1ca098f21
> Pas de PDF pour les services non publiés

- src/routes/_homepage/_landing.svelte
- src/routes/_homepage/_search-form.svelte
https://www.notion.so/dora-beta/HP-Mise-en-avant-Accompagnateur-12833951d2874362beddc5699b5f98a0
> Modification landing page

- src/lib/utils/phone.ts
https://sentry.incubateur.net/organizations/betagouv/issues/10333/?project=12
https://trello.com/c/OqhpCIF1/16-page-structure-crashe-quand-le-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-est-incorrect
> Corrige le formatage des numéros de téléphone incorrects

- src/lib/components/modal.svelte
Reprise de la correction de Marc
> Retrait overflow=hidden à la fermeture de la modal

- src/routes/mon-compte/_notif-improve.svelte
https://trello.com/c/8NTpk6rQ/34-affichage-permanent-du-sondage-dam%C3%A9lioration-de-dora
> Modification du formulaire 'Participer à Dora'

- src/lib/schemas/service.js
Évite d'envoyer à Sentry des avertissements sur la qualité des données,
qui seront mieux gérés par les scripts de nettoyage
https://sentry.incubateur.net/organizations/betagouv/issues/5720/
https://trello.com/c/ROtxkGaT/19-missing-servicesoptions-in-rules-check
> Supprime un avertissement Sentry

- src/lib/utils/index.ts
https://trello.com/c/mqILAlKV/213-error-unexpected-token-in-json-at-position-1
> Evite de déclencher une exception lors de la reception d'une page d'erreur

- src/lib/utils/choice.ts
https://trello.com/c/rz0fi5Lb/198-lors-de-la-cr%C3%A9ation-ou-de-l%C3%A9dition-de-services-ils-y-a-des-entr%C3%A9es-tous-les-besoins-dans-le-champ-besoin-qui-ne-sont-pas-accept%C3%A9
> Évite de muter la liste des besoins quand on rajoute les options "Tous…"

- src/lib/components/structures/search-by-commune.svelte
- src/lib/components/structures/search.svelte
- src/routes/contribuer/form/fields.svelte
https://trello.com/c/wbVY8dBQ/211-contribution-page-de-choix-de-structure
> Change le label de la recherche de structure dans le formulaire de contribution

- src/routes/structures/[slug]/+page.svelte
> N'affiche que 3 services sur le dashboard

- src/lib/components/services/form/fields-inclusion-numerique.svelte
[Peek 2022-11-30 12-12.webm](https://user-images.githubusercontent.com/68475403/204783205-352d6bb0-ae1f-446f-b0c6-b90df32f9205.webm)
> feat: ajout des champs pour l'adresse dans le formulaire de l'inclusion numérique

- src/lib/components/form/field-wrapper.svelte
- src/lib/components/forms/addable-multiselect.svelte
- src/lib/components/forms/field.svelte
- src/lib/components/forms/fieldset.svelte
- src/lib/components/forms/input.svelte
- src/lib/components/forms/simple-autocomplete.svelte
- src/lib/components/services/form/field-model.svelte
- src/lib/components/services/form/fields-common.svelte
> Corrections de l'UI du formulaire de saisie de services

- src/lib/utils/misc.ts
- src/tests/addlinkToUrls.test.ts
Avec les tests unitaires associés !
> Ajout 'target=blank' dans les urls

- .husky/pre-commit
- vite.config.ts
From : https://github.com/sveltejs/kit/issues/8996
> Correction des tests unitaires

- src/lib/components/display/notice.svelte
- src/lib/components/specialized/services/field-category.svelte
- src/lib/components/specialized/services/fields-contact.svelte
- src/lib/components/specialized/services/fields-perimeter.svelte
- src/lib/components/specialized/services/fields-presentation.svelte
- src/lib/components/specialized/services/fields-typology.svelte
- src/lib/validation/schema-utils.ts
- src/lib/validation/schemas/service.ts
- src/routes/services/service-edition-form.svelte
- tailwind.config.cjs
https://trello.com/c/iAl2N9Z0/358-limitation-%C3%A0-3-th%C3%A9matiques
> Limitation des services à trois thématiques

- src/routes/structures/[slug]/editer/+page.ts
- src/routes/structures/[slug]/informations.svelte
> Les collaborateurs d'une structure ne peuvent pas l'editer

- src/routes/modeles/model-edition-form.svelte
https://trello.com/c/xtzpwhWm/630-votre-mod%C3%A8le-comporte-plus-de-3-th%C3%A9matiques-visible-m%C3%AAme-quand-ce-nest-pas-le-cas
> Affichage conditionnel du message indiquant plus 3 de thématiques

- src/lib/components/inputs/opening-hours/day-field.svelte
- src/lib/components/inputs/opening-hours/days-grid.svelte
- src/lib/components/inputs/opening-hours/toggle.svelte
- src/lib/consts.ts
- src/lib/types.ts
- src/lib/utils/opening-hours.ts
- src/lib/validation/schema-utils.ts
- src/lib/validation/schemas/structure.ts
> Correction du formulaire des horaires d'ouverture

- src/routes/auth/connexion/+page.svelte
- tailwind.config.cjs
https://trello.com/c/05xwoJLz/646-inclusion-connect-corriger-la-couleur-au-hover-du-bouton
> Inclusion-Connect: changement de couleur au survol

- src/lib/types.ts
- src/lib/utils/service.ts
https://trello.com/c/C7NepBv9/654-data-inclusion-delta-de-th%C3%A9matiques-entre-data-inclusion-et-dora
> Adaptation des logos aux nouvelles thématiques

- src/routes/structures/[slug]/header.svelte
- src/routes/structures/[slug]/informations.svelte
- src/routes/structures/[slug]/quick-start.svelte
https://trello.com/c/pMswYazN/234-fiche-structure-onboarding-empty-spaces
> Corrections onboarding

- src/lib/components/specialized/favorite-icon.svelte
- src/routes/services/[slug]/service-header.svelte
- src/routes/structures/[slug]/services/service-card.svelte
https://trello.com/c/lMUS9Gfb/665-bug-daffichage-ic%C3%B4ne-ajouter-aux-favoris
> Ajustement du responsive du bouton favori

- src/routes/services/[slug]/service-toolbar.svelte
https://trello.com/c/NyfrfMlQ/660-lag-des-infos-dactualisation-sur-la-page-services
> Correction du statut d'actualisation du service : couleur + affichage du status côté navigateur

- src/lib/components/display/notice.svelte
- src/routes/mon-compte/+page.svelte
- src/routes/mon-compte/notif-improve.svelte
https://trello.com/c/J2OuHLVF/397-page-mon-compte-design-et-accessibilit%C3%A9
> a11y : page 'Mon compte'

- src/routes/mon-compte/+page.svelte
https://trello.com/c/Di1fjbcb/691-permettre-la-modification-des-informations-utilisateur-sur-ic
> Meilleure gestion du responsive sur la page "Mon compte"

- src/lib/components/forms/form.svelte
https://trello.com/c/wQ6QFUoV/626-alerte-enregistrement-%C3%A0-la-saisie-sortie-du-formulaire
> Désactivation de la modale avant la redirection

- src/routes/structures/[slug]/+layout.ts
https://trello.com/c/yXRzYbY6/733-appel-%C3%A0-structure-members-en-401-ne-pas-faire-les-appels
La requête est faite en permanence - même quand cela n'est pas pertinent… 😓
> Optimisation de la récupération des membres d'une structure

- src/lib/components/specialized/services/fields-contact.svelte
https://trello.com/c/RHS4XOdL/714-contacts-publics-formulaire-de-saisie
> Mise à jour des labels pour le bloc informations publiques

- src/routes/auth/rattachement/+page.svelte
https://trello.com/c/K67f6gz1/724-clignotement-auth-rattachement
> Rafraîchissement des données au lieu d'un reconnexion

- src/routes/structures/[slug]/+layout.ts
https://trello.com/c/IlKWiOX2/254-visited-structures-devrait-%C3%AAtre-d%C3%A9dupliqu%C3%A9
> Deduplicate visited structures

- src/lib/components/display/text-clamp.svelte
- src/routes/(modeles-services)/_common/display/service-login-notice.svelte
- src/routes/(modeles-services)/_common/display/service-share.svelte
- src/routes/+page.svelte
- src/routes/structures/[slug]/services/service-card.svelte
https://trello.com/c/ywmzb6tD/371-a11y-homepage
https://trello.com/c/TIjUWC57/377-a11y-page-structure-services-structure-informations
https://trello.com/c/j4cd08W2/376-a11y-page-daffichage-dun-service
> Améliorations de l'accessibilité : structures et homepage

- src/lib/components/display/centered-grid.svelte
- src/lib/components/display/relative-date-label.svelte
- src/routes/(modeles-services)/services/[slug]/+page.svelte
- src/routes/(modeles-services)/services/[slug]/service-header.svelte
- src/routes/_index/header.svelte
- src/routes/structures/[slug]/+layout.svelte
- src/routes/structures/[slug]/header.svelte
https://trello.com/c/I8uFGK8O/754-pdfs-fiches-services-cass%C3%A9s-en-prod-le-titre-du-service-nest-pas-lisible
> Correction page d'impression service et structure

- src/routes/_index/sub-menu.svelte
https://trello.com/c/P9R2nd8P/228-mettre-en-place-le-nouveau-header
> Ajout de liens sur le header

- src/routes/_index/sub-menu.svelte
https://trello.com/c/YMHwT4p2/778-modifier-le-lien-communaut%C3%A9-de-linclusion-sur-le-header
> Mis à jour du lien "Communauté de l'inclusion"

- src/app.postcss
- src/lib/components/display/fieldset.svelte
- src/lib/components/forms/field-wrapper.svelte
- src/lib/components/forms/fields/addable-multiselect-field.svelte
- src/lib/components/forms/fields/basic-input-field.svelte
- src/lib/components/forms/fields/textarea-field.svelte
- src/lib/components/inputs/checkboxes.svelte
- src/lib/components/inputs/obsolete/select-field.svelte
- src/lib/components/inputs/radio-buttons.svelte
- src/lib/components/inputs/rich-text/button.svelte
- src/lib/components/inputs/rich-text/editor.svelte
- src/lib/components/inputs/select/simple-autocomplete.svelte
- src/routes/(modeles-services)/_common/fields-documents.svelte
- src/routes/(modeles-services)/_common/fields-modalities.svelte
https://trello.com/c/NYROt5vZ/372-a11y-r%C3%A9sultats-de-recherche
> A11y create service

- src/lib/components/forms/field-wrapper.svelte
- src/lib/components/forms/fields/addable-multiselect-field.svelte
- src/lib/components/forms/fields/basic-input-field.svelte
- src/lib/components/forms/fields/boolean-radio-buttons-field.svelte
- src/lib/components/forms/fields/checkboxes-field.svelte
- src/lib/components/forms/fields/multi-select-field.svelte
- src/lib/components/forms/fields/radio-buttons-field.svelte
- src/lib/components/forms/fields/select-field.svelte
- src/lib/components/forms/fields/textarea-field.svelte
- src/lib/components/inputs/checkboxes.svelte
- src/lib/components/inputs/radio-buttons.svelte
- src/lib/components/inputs/select/select.svelte
- src/lib/components/inputs/select/simple-autocomplete.svelte
- src/lib/validation/validation.ts
https://trello.com/c/rtPNtzU8/386-a11y-page-cr%C3%A9ation-dun-service
> Erreurs de formulaires lié aux champs via aria-describedby

- src/routes/(modeles-services)/modeles/model-edition-form.svelte
- src/routes/structures/[slug]/services/list.svelte
- src/routes/structures/[slug]/services/services-to-update-notice.svelte
https://trello.com/c/kBWAkQIa/627-mise-%C3%A0-jour-en-masse-des-services-via-les-mod%C3%A8les
> Corrections sur la mise à jour en masse des modèles

- src/routes/(modeles-services)/_common/display/small-service-share.svelte
- src/routes/(modeles-services)/services/[slug]/service-header.svelte
Suite aux retours d'Andrei : https://trello.com/c/99aQni8p/743-fiche-service-a-b-testing
> Ajustement des favoris pour l'AB-Testing

- src/lib/utils/plausible.ts
- src/routes/(modeles-services)/_common/display/service-body.svelte
- src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
- src/routes/(modeles-services)/_common/display/small-service-share.svelte
https://trello.com/c/99aQni8p/743-fiche-service-a-b-testing
(il n'y a pas toutes les modifications d'Andrei mais le minimum pour une MEP)
> Amélioration du design des services pour l'AbTesting

- src/lib/components/specialized/services/set-as-updated-modal.svelte
https://trello.com/c/5WlSj1Mh/800-bug-confirmer-sur-la-modale-marquer-comme-%C3%A0-jour
> Gestion des overflow sur la modal d'actualisation

- src/lib/components/specialized/services/display/new/service-contact.svelte
- src/lib/components/specialized/services/service-contact.svelte
- src/routes/(modeles-services)/_common/display/service-login-notice.svelte
- src/routes/(modeles-services)/_common/display/small-service-share.svelte
https://trello.com/c/mvyQkrXB/795-corrections-de-design-sur-lab-testing
> Service design fixes

- src/lib/components/hoc/modal.svelte
- src/lib/components/specialized/services/inclusion-num-switch.svelte
- src/lib/components/specialized/services/set-as-updated-modal.svelte
- src/lib/components/user/user-main-activity-modal.svelte
- src/routes/(modeles-services)/modeles/model-edition-form.svelte
- src/routes/admin/structures/structure-modal.svelte
https://trello.com/c/eC9JvpVJ/811-correction-pop-in-profil-utilisateur
> Gabarit "medium" pour la modale

- src/lib/utils/orientation.ts
- src/routes/(modeles-services)/services/[slug]/orienter/demande/+page.svelte
- src/routes/(modeles-services)/services/[slug]/orienter/demande/orientation-form.svelte
- src/routes/(modeles-services)/services/[slug]/orienter/merci/+page.svelte
- src/routes/(modeles-services)/services/[slug]/orienter/validation-form.svelte
- src/routes/orientations/+page.svelte
- src/routes/orientations/accept-orientation-modal.svelte
- src/routes/orientations/contact-beneficiary-modal.svelte
- src/routes/orientations/contact-prescriber-modal.svelte
- src/routes/orientations/handle-orientation.svelte
- Ajuster les paramètres des requêtes pour ContactPrescriber/ContactBeneficiary
- BUG 20 : les publics ne remontent pas dans l'étape 1 
- Notice téléchargement => design a corrigé
- BUG 21 Document à télécharger dans un nouvel onglet
- Correctif 10 : pas de message d'informations sur les pièces-jointes
- Correctif 11 : supprimer "Ajouter en copie le conseiller ou la conseillère référente" si CR = accompagnateur lorsqu'on souhaite contacter le bénéficiaire 
- BUG : Valider la demande => Pas un bug :x:
- CORRECTIF 12 : quand le benef n'a pas d'email -> ne pas laisser la possibilité d'ajouter une msg de réponse lors de la validation au benef
- CORRECTION : notice pour informer le bénéficiaire
Il manquera la partie "Mail personnalisé" et les liens pour les pièces-jointes (edit: que tu es en …
> Premières corrections des mails

- src/lib/components/forms/form.svelte
- src/lib/types.ts
- src/lib/utils/orientation-templates.ts
- src/lib/utils/orientation.ts
- src/routes/(modeles-services)/services/[slug]/orienter/demande/orientation-form.svelte
- src/routes/(modeles-services)/services/[slug]/orienter/validation-form.svelte
- src/routes/orientations/accept-orientation-modal.svelte
- src/routes/orientations/contact-prescriber-modal.svelte
- src/routes/orientations/deny-orientation-modal.svelte
- src/routes/orientations/handle-orientation.svelte
- Mails personnalisés
- remplacement de `ultérieurement` par `lors de la deuxième étape de ce formulaire.`
-bouton `Ajouter le ou la bénéficiaire en copie` que s'il a un email connu
> Mails personnalisés

- src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
https://trello.com/c/mvyQkrXB/795-corrections-de-design-sur-lab-testing
> Design bleu : pas de border au hover

- src/routes/(modeles-services)/services/[slug]/orienter/demande/+page.svelte
- src/routes/(modeles-services)/services/[slug]/orienter/demande/orientation-form.svelte
https://trello.com/c/G8OauuoG/850-orientation-supprimer-lobligation-de-joindre-un-pj
> Plus de validation pour le téléversement

- src/routes/_index/sub-menu.svelte
https://trello.com/c/gqIsh28B/819-modifier-le-lien-vers-la-communaut%C3%A9-dora
> Modification lien Communauté de l’inclusion

- src/lib/types.ts
- src/routes/admin/structures/filters.svelte
https://trello.com/c/I3QGUAHB/818-gestionnaire-de-territoire-ajouter-les-labels-nationaux-comme-filtre-avanc%C3%A9
> Filtre des labels nationaux pour les gestionnaires

- src/routes/(static)/politique-de-confidentialite/content.md
https://trello.com/c/tIj9g804/870-modification-pdc-orientation
J'en ai profité pour corriger les apostrophes
> Mise à jour de la politique de confidentialité

- src/lib/components/specialized/services/fields-publics.svelte
https://trello.com/c/0sZT4MKS/867-1er-%C3%A9tape-de-suppression-des-crit%C3%A8res-et-publics-sp%C3%A9cifiques
> Retrait de l'ajout de valeurs spécifiques pour les public et critères

- src/routes/admin/structures/+page.svelte
https://trello.com/c/4ylEzUvP/871-tdb-gestionnaire-filtre-sur-le-d%C3%A9partement-ne-fonctionne-plus
=> Le ticket passera en action post-mep ensuite :)
> Lien metabase => lieu devient département

- src/lib/types.ts
- src/lib/utils/service-search.ts
- src/routes/recherche/+page.ts
https://trello.com/c/mphcUDmV/878-activation-de-la-recherche-di-en-permanence
> Retrait du paramètre useDI

- src/lib/components/display/relative-date-label.svelte
- src/lib/components/inputs/geo/city-search.svelte
- src/lib/components/inputs/opening-hours/day-field.svelte
- src/lib/components/inputs/uploader.svelte
- src/lib/components/specialized/establishment-search/search.svelte
- src/lib/components/specialized/services/contact-email.svelte
- src/lib/components/specialized/services/display/extended-service-key-informations.svelte
- src/lib/components/specialized/services/display/service-key-informations.svelte
- src/lib/components/specialized/services/fields-publics.svelte
- src/lib/components/specialized/services/inclusion-num-switch.svelte
- src/lib/components/user/user-main-activity-form.svelte
- src/lib/utils/partners.ts
- src/routes/(modeles-services)/_common/display/service-presentation.svelte
- src/routes/(modeles-services)/_common/fields-inclusion-numerique.svelte
- src/routes/(modeles-services)/modeles/creer/+page.svelte
- src/routes/(modeles-services)/services/creer/+page.svelte
- src/routes/(modeles-services)/services/creer/+page.ts
- src/routes/(static)/accessibilite/+page.svelte
- src/routes/(static)/cgu/cgu-20221213/content.md
- src/routes/(static)/cgu/cgu-20230515/content.md
- src/routes/(static)/cgu/content.md
- src/routes/+page.svelte
- src/routes/_index/header.svelte
- src/routes/_index/menu.svelte
- src/routes/contribuer/merci/+page.svelte
- src/routes/structures/[slug]/services/service-card.svelte
- src/routes/structures/structure-edition-fields.svelte
- src/tests/utils/date/computeRelativeDateLabel.test.ts
https://trello.com/c/7ZIzyg9T/813-remplacer-par-des-dans-le-front-et-le-back
> Utilisation de la bonne typographie d'apostrophes

- src/routes/structures/[slug]/pending-notice.svelte
https://trello.com/c/oXUU5uyb/872-modification-de-la-phrase-sur-lihm-auth-rattachement
> Mise à jour de la phrase de rattchement

- src/routes/admin/structures/+page.svelte
> Ajout des thématiques dans l'export xlsx du tdb

- src/lib/components/specialized/services/field-category.svelte
- src/lib/components/specialized/services/inclusion-num-switch.svelte
https://trello.com/c/Vs2Whae3
Alternative à #338 
@AlexandreCantin voir ce commentaire: https://github.com/gip-inclusion/dora-front/pull/338#issuecomment-1727533137
> Version alternative de la correction du basculement de formulaire Inclusion Numérique

- src/lib/requests/admin.ts
- src/lib/requests/services.ts
- src/routes/admin/moderation/+page.svelte
Proche mais hors-sujet vis-à-vis de :
https://trello.com/c/q3dwAGpz/76-nettoyer-les-endpoints-qui-ne-sont-plus-utilis%C3%A9s-par-le-front
> Retrait de code non utilisé

- src/lib/components/forms/fields/addable-multiselect-field.svelte
- src/lib/components/forms/fields/basic-input-field.svelte
- src/lib/components/forms/fields/textarea-field.svelte
- src/lib/components/specialized/services/fields-contact.svelte
- src/lib/utils/misc.ts
- src/lib/validation/schema-utils.ts
https://trello.com/c/jfv1BOMy/929-corrections-saisie-service-t%C3%A9l%C3%A9phone
> Ajout de maxLength sur les champs textuels

- src/lib/components/display/breadcrumb.svelte
- src/lib/components/inputs/obsolete/select-field.svelte
- src/lib/components/inputs/rich-text/editor.svelte
- src/lib/components/specialized/services/contact-email.svelte
- src/lib/components/specialized/services/contact-phone.svelte
- src/lib/components/specialized/services/fields-address.svelte
- src/lib/components/specialized/services/fields-place.svelte
- src/routes/(modeles-services)/_common/fields-documents.svelte
- src/routes/favoris/+page.svelte
- src/routes/mes-alertes/+page.svelte
- src/routes/structures/[slug]/collaborateurs/member.svelte
- src/routes/structures/[slug]/modeles/model-button-menu.svelte
- src/routes/structures/[slug]/services/service-button-menu.svelte
https://trello.com/c/rtPNtzU8/386-a11y-page-cr%C3%A9ation-dun-service
> Correction de problèmes d'accessibilité

- src/lib/types.ts
- src/routes/admin/structures/+page.svelte
- src/routes/admin/structures/filters.svelte
- src/routes/admin/structures/structures-table.svelte
- src/routes/admin/structures/types.ts
https://trello.com/c/H95GIKGs/955-evolutions-espace-gestionnaire-de-territoire-bouton-structure-obsol%C3%A8te
> Permettre de rendre des structures obsolètes

- src/lib/utils/plausible.ts
- src/lib/utils/stats.ts
- src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
- src/routes/(modeles-services)/services/[slug]/+page.svelte
- src/routes/(modeles-services)/services/di/[id]/+page.svelte
- src/routes/recherche/+page.svelte
- src/routes/recherche/+page.ts
- src/routes/recherche/search-result.svelte
https://trello.com/c/1jAJLv1s/975-tracker-l%C3%A9venement-recherche-qui-a-amen%C3%A9-%C3%A0-la-visualisation-dun-service
> Suivi de l'id de recherche dans les événements de mesure d'audience

- src/lib/components/display/breadcrumb.svelte
- src/lib/requests/saved-search.ts
- src/lib/types.ts
- src/routes/mes-alertes/[searchId]/+page.svelte
- src/routes/mes-alertes/[searchId]/+page.ts
- src/routes/mes-alertes/description.svelte
- src/routes/mes-alertes/saved-search-card.svelte
- src/routes/mes-alertes/title.svelte
- src/routes/recherche/search-result.svelte
https://trello.com/c/F3PdrFwE/982-alertes-v2
PR back : https://github.com/gip-inclusion/dora-back/pull/187
> Alertes v2

- src/lib/consts.ts
- src/routes/(modeles-services)/services/[slug]/+page.svelte
- src/routes/+layout.svelte
- src/routes/recherche/+page.svelte
- src/routes/structures/[slug]/+layout.svelte
> Suppression du NPS et du formulaire utilisateurs anonymes

- src/lib/components/specialized/establishment-search/search.svelte
- src/lib/consts.ts
- src/lib/validation/schema-utils.ts
- src/lib/validation/schemas/dashboard.ts
> Renomme Pôle Emploi en France Travail

- src/lib/components/specialized/services/display/service-key-informations.svelte
- src/routes/(modeles-services)/_common/display/service-body.svelte
> Correction du défilement sur la page services

- src/lib/components/forms/fields/city-search-field.svelte
- src/lib/components/inputs/geo/city-search.svelte
- src/lib/components/inputs/select/select.svelte
- src/lib/components/inputs/select/simple-autocomplete.svelte
- src/lib/components/specialized/establishment-search/search-by-commune.svelte
https://trello.com/c/cHrSWgGU
PR back : https://github.com/gip-inclusion/dora-back/pull/255
> Améliore l’affichage des résultats de recherche Sirene

- src/lib/types.ts
- src/lib/utils/stats.ts
- src/routes/structures/[slug]/informations.svelte
https://trello.com/c/AdUpKeu8/47-modalit%C3%A9s-dorientation-fiche-structure
assorti du tracking (considéré comme une MeR)
> fiche structure: ajout d'un bouton pour visualiser les infos de contact

- src/lib/types.ts
- src/lib/utils/orientation.ts
- src/routes/orientations/+page.svelte
- src/routes/orientations/+page.ts
- src/routes/orientations/accept-orientation-modal.svelte
- src/routes/orientations/contact-beneficiary-modal.svelte
- src/routes/orientations/contact-prescriber-modal.svelte
- src/routes/orientations/deny-orientation-modal.svelte
- src/routes/orientations/handle-orientation.svelte
- src/routes/orientations/link-expired.svelte
- vite.config.ts
https://trello.com/c/pkbb8zRI/50-lien-dacc%C3%A8s-%C3%A0-la-page-recap-demande-dorientation-aipd
Ajout de la création d'un "lien magique" vers les orientations pour les structures porteuses d'un service.
> Ajout d'un lien "magique" pour la demande d'orientation

- src/lib/components/specialized/services/display/service-key-informations.svelte
https://trello.com/c/L9Dfbjdb/42-cr%C3%A9er-modifier-un-service-info-rg-sur-choix-type-de-service-et-son-affichage
> fix: tri de l'affichage des types dans le détail d'un service

- src/lib/components/forms/fields/checkboxes-field.svelte
- src/lib/components/inputs/checkbox.svelte
- src/lib/components/inputs/checkboxes.svelte
- src/lib/components/specialized/services/field-model.svelte
- src/lib/types.ts
- src/lib/validation/schemas/service.ts
- src/routes/(modeles-services)/_common/fields-modalities.svelte
- src/routes/(modeles-services)/services/creer/+page.ts
- src/routes/recherche/result-filter.svelte
- tailwind.config.cjs
Modalités d'orientation : fiche service
- [Trello](https://trello.com/c/KUZ3FJKi/49-modalit%C3%A9s-dorientation-configuration-niveau-service-affichage-sur-fiche-service)
- [Figma](https://www.figma.com/design/dLG2uynZEceGHsKtnvPpxn/Fiche-service---Mobilisation?node-id=1739-2969&m=dev)
> Modalités d'orientation : formulaire d'édition d'un service

- .eslintrc.cjs
- .github/workflows/ci.yml
- package.json
- src/lib/components/display/hamburger.svelte
- src/lib/components/forms/fields/address-search-field.svelte
- src/lib/components/forms/fields/admin-division-search-field.svelte
- src/lib/components/forms/fields/boolean-radio-buttons-field.svelte
- src/lib/components/forms/fields/hidden-field.svelte
- src/lib/components/forms/fields/opening-hours-field.svelte
- src/lib/components/forms/fields/rich-text-field.svelte
- src/lib/components/forms/sticky-form-submission-row.svelte
- src/lib/components/inputs/opening-hours/day-field.svelte
- src/lib/components/inputs/opening-hours/toggle.svelte
- src/lib/components/specialized/services/display/subcategory-list-item.svelte
- src/lib/components/specialized/services/field-model.svelte
- src/lib/components/specialized/services/fields-presentation.svelte
- src/lib/components/specialized/services/synchronized-icon.svelte
- src/lib/components/specialized/services/update-status-icon.svelte
- src/lib/components/specialized/structure-card.svelte
- src/routes/_index/footer.svelte
- src/routes/_index/menu-mes-structures.svelte
- src/routes/_index/menu.svelte
- src/routes/_index/skip-link.svelte
- src/routes/_index/sub-menu.svelte
- src/routes/contribuer/+page.svelte
- src/routes/recherche/result-filters.svelte
- src/routes/structures/[slug]/collaborateurs/member-invited.svelte
- src/routes/structures/[slug]/collaborateurs/member-to-confirm.svelte
- src/routes/structures/[slug]/count.svelte
- src/routes/structures/[slug]/modeles/model-card.svelte
Le worflow implémenté effectue les actions suivantes pour chaque _push_ et ouverture de PR sur toutes les branches : 
1. Checkout repository
2. Use Node.js 18.x
3. Install dependencies
4. Check formatting
5. Lint code
6. Run tests
7. Build project
> Mise en place d'une CI

- src/lib/components/specialized/services/inclusion-num-switch.svelte
- src/lib/types.ts
- src/routes/(modeles-services)/_common/fields-modalities.svelte
La suppression effective du pass numérique est faite dans https://github.com/gip-inclusion/dora-back/pull/370
> Suppression du code lié au type de frais obsolète « Pass numérique »

- src/routes/recherche/search-result.svelte
- src/routes/recherche/search-results.svelte
- Suppression de l'expérimentation Matomo de redirection vers le formulaire d'orientation ;
- Suppression du lien _Voir la fiche détaillée_.
> AB Test : stop et renvoie vers Fiche Service Vs. Formulaire
