src/routes/_homepage/_landing.svelte, src/routes/_layout/_footer.svelte, src/routes/_layout/_header.svelte, src/routes/auth/registration/_step3-confirm.svelte, src/routes/contribuer/merci.svelte, src/routes/structures/[slug]/_informations.svelte
- Les attributs `alt` ne doivent être remplis que si l'image est porteuse d'informations ou contient du texte (aka. pas une illustration)
- Il est nécessaire de préciser `title="Ouverture dans une nouvelle fenêtre"` en cas de `target="_blank"`
=> feat(a11y): améliorations alt et précision nouvelle fenêtre si target=blank

src/routes/contribuer/form/_form-wrapper.svelte
L'identifiant de la suggestion n'était pas assez pratique pour Aurélie
=> fix: slug pour contribution

src/lib/components/rich-text/editor.svelte, src/lib/components/services/body/presentation/service-description.svelte, src/lib/utils.js, src/routes/structures/[slug]/_informations.svelte, tests/markdownToHTML.test.ts
Pour permettre de créer une hiérarchie de titre cohérente sans être pertubé par le Wysiwyg :) 
https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33
=> a11y: Niveau titre paramétrable dans les wysiwyg

src/routes/structures/[slug]/_informations.svelte
https://trello.com/c/JECATcgd/2-cacher-le-cadre-informations-pratiques-des-structures-lorsquil-est-vide
\+ suppression du \<hr\> au dessus de la description longue si elle est manquante
=> Masque le bloc d'info des structures quand il est vide

src/lib/auth.js, src/routes/__layout.svelte
Lors du passage à Inclusion Connect, le paramètre `url` a été rajouté à la fonction `load` du layout principal
https://github.com/betagouv/dora-front/commit/ac826906#diff-c3a76f211b02106e458d330c6c4dfb09844e51487170b2300cf76913360eda47R19
En conséquence, chaque changement d'url relançait le `load`, qui faisait une revalidation complète de l'utilisateur, via `validateCredsAndFillUserInfo`.
Les effets de bord étaient nombreux, par exemple à travers le composant EnsureLoggedIn, qui reconstruisait tous ses descendants au passage:
https://github.com/betagouv/dora-front/blob/main/src/lib/components/ensure-logged-in.svelte#L24
Solution: la validation n'est faite que si le store userInfo n'est pas encore initialisé, ce qui arrive lors du chargement initial, ou après logout.
Tickets affectés: 
- …
=> Arrete de revalider l'utilisateur à chaque changement de page

src/lib/components/breadcrumb.svelte
https://trello.com/c/QFs9lfyc/56-breadcrumbs-le-clic-sur-le-nom-de-la-structure-ne-ram%C3%A8ne-pas-sur-la-structure
=> Fil d'Ariane : pas d'onglet informations

src/lib/components/form/select/select-field.svelte, src/lib/components/structures/form-wrapper.svelte, src/routes/structures/[slug]/index.svelte, src/routes/structures/[slug]/services/_list.svelte, src/routes/structures/[slug]/services/index.svelte
https://trello.com/c/hXvZRv1f
Lors du passage d'un filtre à l'autre, on ne repartait pas de l'ensemble de la liste des services, mais de la liste filtrée.
Ça aurait pu être corrigé plus simplement, mais j'en ai profité pour corriger deux sources de confusion:
- dans le composant _list.svelte, on passait à la fois la structure et la liste des services
```
<List
services={$structure.services || []}
structure={$structure}
...
/>
```
Mais une fois dans le composant, on utilisait `structure.services` pour se réferrer à la liste non filtrée, et on écrasait `services` avec la liste filtrée.
Je ne passe maintenant plus que la structure, et on utilise toujours explicitement structure.services dans le composant.
- la réactivité était un peu extrême -- j'ai préféré passer par un handler pour mieux …
=> Corrige le rafraichissement des services lors du filtrage

src/routes/favoris/bookmark-card.svelte, src/routes/recherche/search-result.svelte
https://trello.com/c/iIAkmSqL/70-am%C3%A9liorer-la-capitalisation-des-noms-de-ville
=> Ne force plus l'affichage des villes en majuscule

src/lib/components/specialized/tally-nps-popup.svelte, src/lib/utils/nps.ts, src/routes/recherche/+page.svelte, src/routes/services/[slug]/+page.svelte, src/routes/structures/[slug]/+layout.svelte
https://trello.com/c/EgvZNnPk/350-ajustement-des-nps-pour-le-gip
Deux soucis :
- le formId n'est plus suffisant pour différencier le NPS
- la fermeture à cause d'une navigation vs clic sur le bouton close appelaient `onClose` dans tous les cas...
=> Corrections du comportement des formulaires NPS

src/routes/structures/[slug]/collaborateurs/member.svelte, src/routes/structures/[slug]/modeles/list.svelte, src/routes/structures/[slug]/services/list.svelte
Nouveaux soucis de responsive lié à (pour les écrans < 450px de large) :
https://trello.com/c/I3avcuJV/233-version-mobile-de-la-fiche-struture-revoir-les-onglets-de-navigation-scroll-horizontal
=> Amélioration responsive sur la page structures

src/lib/components/specialized/services/field-model.svelte, src/lib/utils/misc.ts, src/routes/admin/contributions/suggestion-modal.svelte, src/routes/admin/services/[slug]/+page.svelte, src/routes/admin/structures/[slug]/+page.svelte, src/tests/markdownToHTML.test.ts
https://trello.com/c/Y4d3Qea2
Quand la description longue d'un modèle contenait au moins un titre, lors de l'instanciation du modèle, la description etait marquée comme modifiée.
Le problème avait lieu dans editor.svelte: le passage par markdownToHTML mettait un niveau de titre minimal à 2 (valeur par défaut de l'argument), et faussait donc la comparaison.
Solution adoptée:
- on enlève la valeur par défaut de `markdownToHTML`; il s'agit d'une mutation qui ne doit etre faite qu'à l'affichage
https://github.com/betagouv/dora-front/pull/219/files#diff-1dd60574449dd8540b7c5eaf7ce59d3fe19835e0e4d1def9cdf6bc5de77c4305R19
- on applique cette valeur coté appelant, chaque fois ou ce n'était pas le cas et où c'est pertinent.
=> Corrige la synchronisation des descriptions lors de l'instanciation d'un modèle

vite.config.ts
J'ai juste fait un `npm i` et c'était bon 🙂
Du coup, je pense que c'était juste des `node_modules` pas à jour...
https://trello.com/c/75Y65Z31/619-correction-vitest
=> Retrait de `inline:"@sveltejs/kit"` pour les tests front

src/lib/components/inputs/select/simple-autocomplete.svelte
https://trello.com/c/TqrGgzCG/740-bug-dropdowns-ne-souvrent-plus-par-d%C3%A9faut
=> Réouverture de la dropdown par défaut

src/routes/(modeles-services)/_common/display/service-body.svelte
Les diff est bordélique… mais en réalité, il y a juste un `{#if browser}` en plus 🤷‍♂️
=> Sidebar uniquement dans le navigateur

src/lib/components/specialized/services/set-as-updated-modal.svelte
(https://trello.com/c/pvpBj1pD/798-modelchanged-doit-prendre-en-compte-les-dates-de-modification-du-service-et-du-mod%C3%A8le)
Il s'avère que la mise à jour via la modale mettait à jour la date de modification sans mettre à jour le `sync_checksum`
=> Mis à jour de sync_checksum via la modale d'actualisation

src/lib/requests/structures.ts
https://trello.com/c/sdjBE8z0/812-probl%C3%A8me-validation-autre-label
Cause :
En back, on a un tableau et une chaîne de caractère en front…
La conversion était bien faite mais on ne gérait pas le tableau vide… et la condition `isString()` du formulaire échouait car on avait un tableau`[]`
=> Correction d'un faux message d'erreur sur "Autres labels"

src/lib/components/hoc/modal.svelte, src/lib/components/inputs/uploader.svelte, src/lib/types.ts, src/lib/utils/file.ts, src/lib/utils/service.ts, src/routes/(modeles-services)/_common/display/service-mobilisation.svelte, src/routes/(modeles-services)/_common/display/service-mobilize.svelte, src/routes/(modeles-services)/services/[slug]/orienter/+page.svelte, src/routes/(modeles-services)/services/[slug]/orienter/contact-box.svelte, src/routes/(modeles-services)/services/[slug]/orienter/demande/+page.svelte, src/routes/(modeles-services)/services/[slug]/orienter/demande/+page.ts, src/routes/(modeles-services)/services/[slug]/orienter/demande/orientation-form.svelte, src/routes/(modeles-services)/services/[slug]/orienter/merci/+page.svelte, src/routes/(modeles-services)/services/[slug]/orienter/store.ts, src/routes/(modeles-services)/services/[slug]/orienter/validation-form.svelte, src/routes/orientations/[id]/+page.svelte, src/routes/orientations/[id]/accept-orientation-modal.svelte, src/routes/orientations/[id]/contact-beneficiary-modal.svelte, src/routes/orientations/[id]/contact-service-modal.svelte, src/routes/orientations/[id]/deny-orientation-modal.svelte, src/routes/orientations/[id]/handle-orientation.svelte, tailwind.config.cjs
- BUG 1 : les mentions de la carte vitale sont absente du formulaire
- Synchronisation entre le `accept` de l'`input[type=file]` et le `placeholder` + acceptation `xls`, `xlsx` et `ods`
- BUG 4 : nom de la PJ à télécharger (demande d'orientation)
- BUG 5 : &nspb; en trop dans le sujet
- BUG 6 : faute d'orthographe sur prescriptrice (demande d'orientation)
- Andrei : règle d'apparition de la notice "Informez le ou la bénéficiaire"
- BUG-8 : retrait de l'en-tête sur les modales de confirmation
- Andrei - corrections 2 : date du jour par défaut pour le champ "Disponibilité" + Textarea "Autre méthode de contact" que si "Autre" est coché dans les préférences
- Redirection sur l'étape 1 si refresh ou accès direct à l'étape 2
- Correctif 7 : &nbsp; en trop sur les motifs de refus
- Bug 8 : …
=> Corrections des premiers retours/bugs sur l'orientation

src/lib/utils/orientation.ts, src/routes/(modeles-services)/services/[slug]/orienter/demande/+page.ts, src/routes/(modeles-services)/services/[slug]/orienter/validation-form.svelte
https://trello.com/c/ncUHC0kc/860-orientation-les-crit%C3%A8res-ne-sont-plus-obligatoires
Le retour arrière du navigateur permettait de retourner à l'étape 2 sans valider le formulaire…
Un cas à la marge mais possible !
=> Revalider le formulaire à l'étape 2 pour gérer les retours navigateurs

src/lib/components/inputs/checkboxes.svelte, src/lib/components/inputs/radio-buttons.svelte
https://trello.com/c/INF19s7S/823-mettre-en-standard-non-pr-les-qpv-zrr-dans-le-formulaire-de-demande
Les valeurs `true` ou `false` étant mise - par erreur - dans le champs `name`, le navigateur ne considérait que le dernier `input`… car considérait ces input dans le même groupe
=> Correction de duplication de name sur les input-radio

package-lock.json, package.json, src/lib/components/specialized/osm-hours.svelte, src/lib/components/specialized/services/display/extended-service-key-informations.svelte, src/lib/components/specialized/services/display/service-key-informations.svelte, src/lib/utils/opening-hours.ts, src/routes/structures/[slug]/informations.svelte
https://trello.com/c/wcNkARYU/875-fr%C3%A9quence-et-horaire-service-interpr%C3%A9ter-si-osm-hours
Exemple de service : https://dora.inclusion.beta.gouv.fr/services/di/soliguide--6181a8118ac6b179ffba2a6b
Le souci principal de cette PR est de détecter la présence du format OSM… et j'ai dû passer par la librairie `opening_hours` qui fonctionne bien mais pèse `317 Ko` 🥶 (64 gzip)
Une alternative serait de juste tester le début de la chaîne (pour vérifier `Mo`, `Tu`…) mais cela serait moins fiable… mais moins lourd !
=> Gestion des osm-hours dans les fréquences et horaires

src/routes/(modeles-services)/_common/fields-inclusion-numerique.svelte
Le paramètre étant ré-écraser dans la méthode `preSaveInclusionNumeriqueService`, le mettre à zéro ici lors du changement du formulaire n'a pas trop de sens…
=> Ne pas écraser "LocationKind" lors du passage sur le formulaire numérique

package-lock.json, package.json, src/lib/components/inputs/select/simple-autocomplete.svelte
https://trello.com/c/aUWThsRh/901-la-mise-%C3%A0-jour-de-svelte-casse-les-select
Le passage à Svelte 3.57.0 cassait plusieurs de nos select; leur onChange était désormais appelé dès l'initialisation avec une valeur nulle.
Le problème a été isolé sur cette ligne:
https://github.com/gip-inclusion/dora-front/blob/a49565a7fa2c44ca8dac8728aa168721fff655fc/src/lib/components/inputs/select/simple-autocomplete.svelte#L730
le `bind` mettait à jour `value`, en changeant sa valeur de `undefined` à `null` ce qui provoquait l'appel de `onValueChanged`
https://github.com/gip-inclusion/dora-front/blob/a49565a7fa2c44ca8dac8728aa168721fff655fc/src/lib/components/inputs/select/simple-autocomplete.svelte#L174
En cherchant une éventuelle solution adoptée dans le code upstream, on voit que ce `bind` n'était …
=> Correction des select avec Svelte > 3.56.0

src/lib/utils/plausible.ts
https://trello.com/c/6EtZcHSP/918-donn%C3%A9e-plausible-%C3%A0-remettre-en-etat
Aucune idée pourquoi j'ai mis le booléen est passé de `true` à `false` (ça sent clairement le copier-coller foireux 😔)
=> Restauration des user-data dans l'évènement plausible "service"

src/routes/orientations/accept-orientation-modal.svelte
https://trello.com/c/AXIASn6A/919-correction-orientation-rendre-le-message-obligatoire-pour-le-b%C3%A9neficiaire-lors-de-la-validation
=> Message pour le bénéficiaire obligatoire

src/lib/components/inputs/geo/admin-division-search.svelte
https://trello.com/c/ltuMmgrI/947-cacher-les-codes-r%C3%A9gions-dans-le-menu-d%C3%A9roulant-des-zones-de-diffusion
=> Retrait du code région dans l'auto-complétion des lieux

src/lib/components/display/dropdown-menu.svelte, src/lib/components/hoc/modal.svelte, src/lib/components/inputs/obsolete/select-options.svelte, src/lib/components/specialized/services/service-state-update-select.svelte, src/routes/_index/sub-menu-dropdown.svelte, src/routes/admin/copyable-text.svelte, src/routes/admin/structures/structures-table.svelte, svelte.config.js
https://trello.com/c/QttaTJyb/917-a11y-reactiver-et-corriger-les-avertissements-daccessibilit%C3%A9
Notes :
1 - un warning me fait de la résistance : celui de la modale qui sert à isoler les clics qui surviennent dans la modale… et évite sa fermeture. L'enlever ferme la modale à chaque clic et le garder génère le warning… 
2 - Les `div` qui servent pour un click_outside ont été mis en `role="presentation"` car, en soi, c'est pas des boutons 🙂
3 - dans `service-state-update-select.svelte`, le `aria-selected` est tout le temps à `false` car la dropdown ne contient le statut courant
=> Réparation des warnings a11y de Svelte

src/routes/(modeles-services)/services/[slug]/orienter/validation-form.svelte
Une mauvaise gestion du cas où `formsInfo` vaut `null` causait le formulaire d'orientation à ne pas s'afficher pour certains services.
=> validation-form: gère le cas où formsInfo vaut null

src/routes/recherche/+page.svelte
Cette PR corrige les deux problèmes suivants :
- Les filtres n'étaient pas correctement pris en compte dans la création d'alertes ;
- Charger directement un lien de recherche causait la dé-sélection des filtres.
=> Correction des filtres

svelte.config.js
Nècessaire pour que les points s'affichent sur la carte
=> svelte.config.js: ajout de data: dans img-src

src/routes/(modeles-services)/services/[slug]/+page.ts
D'un jour à l'autre, un service DI peut disparaître. On ne veut donc pas qu'ils soient indexés.
=> Page service : indexation désactivée pour les services DI

src/routes/structures/[slug]/services/list.svelte
Sur la vue `/structures/:slug/services`, le bouton _Tout effacer_ réinitialisait bien les sélecteurs mais pas le paramètre GET `update-status` et la liste des services affichés. Cette PR corrige ça.
=> Liste des services: corrige comportement bouton Tout effacer

src/lib/components/specialized/services/display/service-key-informations.svelte
Certains services D·I ne disposent pas de la donnée, et incorrectement
bordé côté DORA.
=> HOTFIX: erreur à l'affichage des types pour certains services D·I

src/routes/(modeles-services)/services/[slug]/orienter/+page.ts
Les règles d'orientation fixées par le back-end sont correctes : les
services FT ne sont *jamais* orientables.
Par contre, l'accès direct au formulaire d'orientation était possible
pour les services non-orientables.
=> [HOTFIX] Le formulaire d'orientation ne doit pas être public

src/routes/recherche/search-result.svelte
Les services DI renvoient une distance entière en km. Elle peut être de 0. Dans ce cas, on affiche _< 1 km_ au lieu de ne pas afficher la distance du tout.
J'en profite pour utiliser des espaces fines insécables là où il faut.
=> SearchResult: affiche distance moins de 1 km

src/lib/components/display/linkify.svelte, src/lib/utils/stats.ts, src/routes/(modeles-services)/_common/display/service-body.svelte, src/routes/(modeles-services)/_common/display/service-mobilisation.svelte, src/routes/(modeles-services)/_common/display/service-mobilize.svelte, src/routes/(modeles-services)/_common/fields-modalities-beneficiary.svelte, src/routes/(modeles-services)/_common/fields-modalities-coach.svelte
- Texte de lien par défaut au lieu d'un placeholder pour le formulaire externe ;
- Affiche le bouton de coordonnées si les infos de contact sont publiques et si il y a une modalité bénéficiaire `telephoner` ou `envoyer-un-mail` ;
- Modification de Linkify pour qu'il émette un événement linkClick au lieu de prendre une prop `trackMobilisationOnLinkClick` ;
- Ajout du lien externe dans les événements de mobilisation.
=> Corrections modalités d'orientation

src/routes/(modeles-services)/services/service-edition-form.svelte
Le formulaire d'édition de service (utilisé en création et modification) ne propose pas la modalité _Via le formulaire DORA_ lorsqu'il est désactivé au niveau de la structure.
=> Modalité orientation / choix par éditeur : masquer le formulaire DORA pour les Agences FT

.eslintignore, .gitignore, .prettierignore, src/routes/(modeles-services)/_common/display/service-mobilize.svelte
Depuis récemment, quand on consulte la page d'un service ne proposant pas de `beneficiariesAccessModes` ou de `coachOrientationModes`, alors la page ne s'affiche pas et une "erreur inattendue" est indiquée.
Ex : [fiche service de monenfant.fr ](https://dora.inclusion.beta.gouv.fr/services/di--monenfant--12859394)
Le problème se situe dans le composant `<ServiceMobilize/>`.
Cette PR ajoute des vérifications d'existence de l'une ou l'autre propriété (_fallback_ vers tableau vide pour la boucle).
=> [Fix] Un défaut de rendu du composant ServiceMobilize empêchait le rendu de toute la page service

src/lib/components/forms/fields/multi-select-field.svelte, src/lib/components/inputs/select/select.svelte, src/lib/components/inputs/select/simple-autocomplete.svelte, src/routes/structures/[slug]/editer/structure-edition-fields.svelte
Des bugs ont été constatés lors de la recette du ticket : 
https://trello.com/c/CVlvfhYh/153-ajouter-label-ft-sur-structures
La gestion de ces options de libellés est assez particulière et avancée.
La solution proposée par cette PR consiste à ajouter une propriété – `fixedItemValues` – au composant de sélection `<SimpleAutocomplete/>` pour gérer des "options fixes".
Une option fixe ne peut être ni sélectionnée, ni retirée (ex : label "France Travail" pour une agence France Travail)
=> [Fix] Correction de la gestion des labels nationaux restreints
